// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  var CND, ICE, assign, badge, copy, debug, declare, echo, help, info, isa, jr, rpr, size_of, type_of, types, urge, validate, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'PIPEDREAMS/FREEZE';

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  info = CND.get_logger('info', badge);

  urge = CND.get_logger('urge', badge);

  help = CND.get_logger('help', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  ({assign, copy, jr} = CND);

  //...........................................................................................................
  types = require('./_types');

  ({isa, validate, declare, size_of, type_of} = types);

  ICE = require('icepick');

  //-----------------------------------------------------------------------------------------------------------
  this.freeze = function(x) {
    return ICE.freeze(x);
  };

  this.thaw = function(x) {
    return ICE.thaw(x);
  };

  this.set = function(x, k, v) {
    return ICE.set(x, k, v);
  };

  this.unset = function(x, k) {
    return ICE.unset(x, k);
  };

}).call(this);

//# sourceMappingURL=freeze.js.map
