// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  var CND, ICE, assign, badge, copy, debug, declare, isa, jr, rpr, size_of, type_of, types, validate;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'PIPEDREAMS/FREEZE';

  debug = CND.get_logger('debug', badge);

  ({assign, copy, jr} = CND);

  //...........................................................................................................
  types = require('./_types');

  ({isa, validate, declare, size_of, type_of} = types);

  ICE = require('icepick');

  //-----------------------------------------------------------------------------------------------------------
  this.freeze = function(x) {
    return ICE.freeze(x);
  };

  this.thaw = function(x) {
    return ICE.thaw(x);
  };

  this.set = function(x, k, v) {
    return ICE.set(x, k, v);
  };

  this.unset = function(x, k) {
    return ICE.unset(x, k);
  };

}).call(this);

//# sourceMappingURL=freeze.js.map
