// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  var $, $async, CND, L, PD, PS, assign, badge, copy, debug, echo, help, info, jr, override_sym, rpr, select, stamp, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'PIPEDREAMS/OVERRIDES';

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  info = CND.get_logger('info', badge);

  urge = CND.get_logger('urge', badge);

  help = CND.get_logger('help', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  ({assign, jr} = CND);

  //...........................................................................................................
  PS = require('pipestreams');

  PD = require('..');

  ({$, $async, select, stamp} = PD);

  //...........................................................................................................
  ({jr, copy, assign} = CND);

  //...........................................................................................................
  override_sym = Symbol.for('override');

  //-----------------------------------------------------------------------------------------------------------
  this.$drain = function(...P) {
    var pipeline;
    pipeline = [];
    pipeline.push($(function(d, send) {
      if (select(d, '~end')) {
        return send(PD.symbols.end);
      } else {
        return send(d);
      }
    }));
    pipeline.push(PS.$drain(...P));
    return PD.pull(...pipeline);
  };

  //###########################################################################################################
  L = this;

  (function() {
    var key, results, value;
/* Mark all methods defined here as overrides: */
    results = [];
    for (key in L) {
      value = L[key];
      results.push(value[override_sym] = true);
    }
    return results;
  })();

}).call(this);

//# sourceMappingURL=overrides.js.map
