// Generated by CoffeeScript 2.3.1
(function() {
  'use strict';
  var $, $async, $collect, CND, PD, assign, badge, copy, debug, echo, help, info, jr, overrides_sym, rpr, select, stamp, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'PIPEDREAMS/OVERRIDES';

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  info = CND.get_logger('info', badge);

  urge = CND.get_logger('urge', badge);

  help = CND.get_logger('help', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  ({assign, jr} = CND);

  //...........................................................................................................
  PD = require('../..');

  ({$, $async, select, stamp} = PD);

  //...........................................................................................................
  ({jr, copy, assign} = CND);

  //...........................................................................................................
  overrides_sym = Symbol.for('override');

  //-----------------------------------------------------------------------------------------------------------
  $collect = function(settings) {
    var collector, defaults;
    collector = null;
    defaults = {
      select: null,
      key: 'collection',
      callback: null
    };
    settings = assign({}, defaults, settings);
    return $(function(d, send) {
      if (select(d, '~collect')) {
        send(d);
        send(PD.new_single_event(settings.key, collector));
        collector = null;
      } else if (((!settings.select) != null) || select(d, settings.select)) {
        if (collector == null) {
          collector = [];
        }
        collector.push(d.value);
      } else {
        send(d);
      }
      return null;
      return null;
    });
  };

}).call(this);

//# sourceMappingURL=overrides.js.map
