// Generated by CoffeeScript 2.4.1
(function() {
  //-----------------------------------------------------------------------------------------------------------
  this.$wrapsignals = function() {
    /*

    ```
    {"value":1,"first":true,"last":true}
    ```

    ```
    {"value":1,"first":true}
    {"value":2,"last":true}
    ```

    ```
    {"value":1,"first":true}
    {"value":2}
    {"value":3}
    {"value":4}
    {"value":5,"last":true}
    ```

    */
    var is_first, last, prv_d;
    is_first = true;
    prv_d = null;
    last = Symbol('last');
    return this.$({last}, (d, send) => {
      if (d === last) {
        if (prv_d != null) {
          if (is_first) {
            prv_d.first = true;
          }
          prv_d.last = true;
          send(prv_d);
        }
      } else {
        if (prv_d != null) {
          send(prv_d);
        }
        prv_d = {
          value: d
        };
        if (is_first) {
          prv_d.first = true;
        }
        is_first = false;
      }
      return null;
    });
  };

}).call(this);

//# sourceMappingURL=wrapsignals.js.map
